### ISSUE TITLE
How to increase session  time

### ISSUE THREAD

**Issue by krowinski** [SourceLabOrg/kafka-webview#103]
Hi, I get automatically logged out it's very irritating when i'm watchin stream and suddenly its stop and when I'm refreshing page I got login page.

How to increase user session time ?

**Comment by Crim** [comment]
So it should be pretty simple.  Edit your config.yaml file and add the following the `server` top level key, adjust the value as needed.

```yaml
server:
  servlet:
    session:
      ## Timeout after 600 seconds
      timeout: 600
```

Let me know if that solves it for you!
