### ISSUE TITLE
use custom config.yml with docker

### ISSUE THREAD

**Issue by nsecrist** [SourceLabOrg/kafka-webview#203]
How can mount a file in a docker container to be used as the config.yml for webview?
Possibly related to #55.

docker-compose.yml
```yml
services:
    kafka.webview:
        image: sourcelaborg/kafka-webview:latest
        container_name: kafka-webview
        volumes:
            - kafkawebview_data:/app/data
            - ./webview-config:{WHAT GOES HERE} # Not sure what goes here.
        expose:
            - "8080"
```

Any help here would be great. Thanks!
